<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>test</RootNamespace>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <Version>1.0.9742.6623</Version>
    <AssemblyVersion>1.0.9742.6623</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\linear-netcore5.vbproj" />
  </ItemGroup>

</Project>
