#Region "Microsoft.VisualBasic::ebe85953879dd81c34930e1d00a29aab, gr\Microsoft.VisualBasic.Imaging\d3js\NamespaceDoc.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 19
    '    Code Lines: 8 (42.11%)
    ' Comment Lines: 8 (42.11%)
    '    - Xml Docs: 100.00%
    ' 
    '   Blank Lines: 3 (15.79%)
    '     File Size: 474 B


    '     Module NamespaceDoc
    ' 
    ' 
    ' 
    '     Module NamespaceDoc
    ' 
    ' 
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Namespace d3js

    ''' <summary>
    ''' d3.js inspired charting helpers: the chart module API together with the chromatic color
    ''' scale utilities.
    ''' </summary>
    Module NamespaceDoc
    End Module
End Namespace

Namespace d3js.SVG.CSS

    ''' <summary>
    ''' The CSS style model used to style the SVG output generated by the d3.js inspired charting
    ''' helpers.
    ''' </summary>
    Module NamespaceDoc
    End Module
End Namespace
