Namespace d3js

    ''' <summary>
    ''' d3.js inspired charting helpers: the chart module API together with the chromatic color
    ''' scale utilities.
    ''' </summary>
    Module NamespaceDoc
    End Module
End Namespace

Namespace d3js.SVG.CSS

    ''' <summary>
    ''' The CSS style model used to style the SVG output generated by the d3.js inspired charting
    ''' helpers.
    ''' </summary>
    Module NamespaceDoc
    End Module
End Namespace
