'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.VisualBasic.Data.csv.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to meta.foundation-version {
        '''  font-family: &quot;/5.4.5/&quot;; }
        '''
        '''meta.foundation-mq-small {
        '''  font-family: &quot;/only screen/&quot;;
        '''  width: 0em; }
        '''
        '''meta.foundation-mq-medium {
        '''  font-family: &quot;/only screen and (min-width:40.063em)/&quot;;
        '''  width: 40.063em; }
        '''
        '''meta.foundation-mq-large {
        '''  font-family: &quot;/only screen and (min-width:64.063em)/&quot;;
        '''  width: 64.063em; }
        '''
        '''meta.foundation-mq-xlarge {
        '''  font-family: &quot;/only screen and (min-width:90.063em)/&quot;;
        '''  width: 90.063em; }
        '''
        '''meta.foundation-mq-xxlarge {
        '''  font-famil [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property foundation() As String
            Get
                Return ResourceManager.GetString("foundation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''	&lt;meta charset=&quot;utf-8&quot;&gt;
        '''	&lt;title&gt;{Title}&lt;/title&gt;
        '''	&lt;link rel=&quot;shortcut icon&quot; href=&quot;http://gcmodeller.org/DNA.ico&quot; /&gt; 
        '''	&lt;style&gt;{CSS}&lt;/style&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''    &lt;div class=&quot;container&quot;&gt; 
        '''		{doc}
        '''	&lt;/div&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property HTML_Template() As String
            Get
                Return ResourceManager.GetString("HTML_Template", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
