<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace></RootNamespace>
    <OptionStrict>Off</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SpikingNNDemo</AssemblyName>
    <NoWarn>42016,41999,42004,42032</NoWarn>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\TensorFlow\TensorFlow.vbproj" />
  </ItemGroup>

</Project>
