' automatically generated by the FlatBuffers compiler, do not modify

Imports FlatBuffers

Namespace feather.fbs

    Friend Class CategoryMetadata
        Implements IFlatbufferObject
        Private __p As Table = New Table()
        Public ReadOnly Property ByteBuffer As ByteBuffer Implements IFlatbufferObject.ByteBuffer
            Get
                Return __p.bb
            End Get
        End Property
        Public Shared Function GetRootAsCategoryMetadata(_bb As ByteBuffer) As CategoryMetadata
            Return GetRootAsCategoryMetadata(_bb, New CategoryMetadata())
        End Function
        Public Shared Function GetRootAsCategoryMetadata(_bb As ByteBuffer, obj As CategoryMetadata) As CategoryMetadata
            Return obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)
        End Function
        Public Sub __init(_i As Integer, _bb As ByteBuffer) Implements IFlatbufferObject.__init
            __p.bb_pos = _i
            __p.bb = _bb
        End Sub
        Public Function __assign(_i As Integer, _bb As ByteBuffer) As CategoryMetadata
            __init(_i, _bb)
            Return Me
        End Function

        ''' The category codes are presumed to be integers that are valid indexes into
        ''' the levels array
        Public ReadOnly Property Levels As PrimitiveArray
            Get
                Dim o = __p.__offset(4)
                Return If(o <> 0, CType((New PrimitiveArray()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb), PrimitiveArray), Nothing)
            End Get
        End Property
        Public ReadOnly Property Ordered As Boolean
            Get
                Dim o = __p.__offset(6)
                Return If(o <> 0, 0 <> __p.bb.Get(o + __p.bb_pos), False)
            End Get
        End Property

        Public Shared Function CreateCategoryMetadata(builder As FlatBufferBuilder, Optional levelsOffset As Offset(Of PrimitiveArray) = Nothing, Optional ordered As Boolean = False) As Offset(Of CategoryMetadata)
            builder.StartObject(2)
            AddLevels(builder, levelsOffset)
            AddOrdered(builder, ordered)
            Return EndCategoryMetadata(builder)
        End Function

        Public Shared Sub StartCategoryMetadata(builder As FlatBufferBuilder)
            builder.StartObject(2)
        End Sub
        Public Shared Sub AddLevels(builder As FlatBufferBuilder, levelsOffset As Offset(Of PrimitiveArray))
            builder.AddOffset(0, levelsOffset.Value, 0)
        End Sub
        Public Shared Sub AddOrdered(builder As FlatBufferBuilder, ordered As Boolean)
            builder.AddBool(1, ordered, False)
        End Sub
        Public Shared Function EndCategoryMetadata(builder As FlatBufferBuilder) As Offset(Of CategoryMetadata)
            Dim o As Integer = builder.EndObject()
            Return New Offset(Of CategoryMetadata)(o)
        End Function
    End Class


End Namespace
