' automatically generated by the FlatBuffers compiler, do not modify


Imports FlatBuffers
Imports System

Namespace Impl.Metadata

    Friend Class Column
        Implements IFlatbufferObject
        Private __p As Table = New Table()
        Public ReadOnly Property ByteBuffer As ByteBuffer Implements IFlatbufferObject.ByteBuffer
            Get
                Return __p.bb
            End Get
        End Property
        Public Shared Function GetRootAsColumn(_bb As ByteBuffer) As Column
            Return GetRootAsColumn(_bb, New Column())
        End Function
        Public Shared Function GetRootAsColumn(_bb As ByteBuffer, obj As Column) As Column
            Return obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)
        End Function
        Public Sub __init(_i As Integer, _bb As ByteBuffer) Implements IFlatbufferObject.__init
            __p.bb_pos = _i
            __p.bb = _bb
        End Sub
        Public Function __assign(_i As Integer, _bb As ByteBuffer) As Column
            __init(_i, _bb)
            Return Me
        End Function

        Public ReadOnly Property Name As String
            Get
                Dim o = __p.__offset(4)
                Return If(o <> 0, __p.__string(o + __p.bb_pos), Nothing)
            End Get
        End Property
        Public Function GetNameBytes() As ArraySegment(Of Byte)?
            Return __p.__vector_as_arraysegment(4)
        End Function
        Public ReadOnly Property Values As PrimitiveArray
            Get
                Dim o = __p.__offset(6)
                Return If(o <> 0, CType((New PrimitiveArray()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb), PrimitiveArray), Nothing)
            End Get
        End Property
        Public ReadOnly Property MetadataType As TypeMetadata
            Get
                Dim o = __p.__offset(8)
                Return If(o <> 0, CType(__p.bb.Get(o + __p.bb_pos), TypeMetadata), TypeMetadata.NONE)
            End Get
        End Property
        Public Function Metadata(Of TTable As {IFlatbufferObject, New})() As TTable
            Dim o = __p.__offset(10)
            Return If(o <> 0, __p.__union(Of TTable)(o), Nothing)
        End Function
        ''' This should (probably) be JSON
        Public ReadOnly Property UserMetadata As String
            Get
                Dim o = __p.__offset(12)
                Return If(o <> 0, __p.__string(o + __p.bb_pos), Nothing)
            End Get
        End Property
        Public Function GetUserMetadataBytes() As ArraySegment(Of Byte)?
            Return __p.__vector_as_arraysegment(12)
        End Function

        Public Shared Function CreateColumn(builder As FlatBufferBuilder, Optional nameOffset As StringOffset = Nothing, Optional valuesOffset As Offset(Of PrimitiveArray) = Nothing, Optional metadata_type As TypeMetadata = TypeMetadata.NONE, Optional metadataOffset As Integer = 0, Optional user_metadataOffset As StringOffset = Nothing) As Offset(Of Column)
            builder.StartObject(5)
            AddUserMetadata(builder, user_metadataOffset)
            AddMetadata(builder, metadataOffset)
            AddValues(builder, valuesOffset)
            AddName(builder, nameOffset)
            AddMetadataType(builder, metadata_type)
            Return EndColumn(builder)
        End Function

        Public Shared Sub StartColumn(builder As FlatBufferBuilder)
            builder.StartObject(5)
        End Sub
        Public Shared Sub AddName(builder As FlatBufferBuilder, nameOffset As StringOffset)
            builder.AddOffset(0, nameOffset.Value, 0)
        End Sub
        Public Shared Sub AddValues(builder As FlatBufferBuilder, valuesOffset As Offset(Of PrimitiveArray))
            builder.AddOffset(1, valuesOffset.Value, 0)
        End Sub
        Public Shared Sub AddMetadataType(builder As FlatBufferBuilder, metadataType As TypeMetadata)
            builder.AddByte(2, metadataType, 0)
        End Sub
        Public Shared Sub AddMetadata(builder As FlatBufferBuilder, metadataOffset As Integer)
            builder.AddOffset(3, metadataOffset, 0)
        End Sub
        Public Shared Sub AddUserMetadata(builder As FlatBufferBuilder, userMetadataOffset As StringOffset)
            builder.AddOffset(4, userMetadataOffset.Value, 0)
        End Sub
        Public Shared Function EndColumn(builder As FlatBufferBuilder) As Offset(Of Column)
            Dim o As Integer = builder.EndObject()
            Return New Offset(Of Column)(o)
        End Function
    End Class


End Namespace
