' automatically generated by the FlatBuffers compiler, do not modify

Imports FlatBuffers

Namespace Impl.Metadata

    Friend Class DateMetadata
        Implements IFlatbufferObject
        Private __p As Table = New Table()
        Public ReadOnly Property ByteBuffer As ByteBuffer Implements IFlatbufferObject.ByteBuffer
            Get
                Return __p.bb
            End Get
        End Property
        Public Shared Function GetRootAsDateMetadata(_bb As ByteBuffer) As DateMetadata
            Return GetRootAsDateMetadata(_bb, New DateMetadata())
        End Function
        Public Shared Function GetRootAsDateMetadata(_bb As ByteBuffer, obj As DateMetadata) As DateMetadata
            Return obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)
        End Function
        Public Sub __init(_i As Integer, _bb As ByteBuffer) Implements IFlatbufferObject.__init
            __p.bb_pos = _i
            __p.bb = _bb
        End Sub
        Public Function __assign(_i As Integer, _bb As ByteBuffer) As DateMetadata
            __init(_i, _bb)
            Return Me
        End Function


        Public Shared Sub StartDateMetadata(builder As FlatBufferBuilder)
            builder.StartObject(0)
        End Sub
        Public Shared Function EndDateMetadata(builder As FlatBufferBuilder) As Offset(Of DateMetadata)
            Dim o As Integer = builder.EndObject()
            Return New Offset(Of DateMetadata)(o)
        End Function
    End Class


End Namespace
