#Region "Microsoft.VisualBasic::03377edca0c177169f23d6e9c5badb5b, Data\BinaryData\Feather\Impl\Metadata\DateMetadata.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 41
    '    Code Lines: 33 (80.49%)
    ' Comment Lines: 1 (2.44%)
    '    - Xml Docs: 0.00%
    ' 
    '   Blank Lines: 7 (17.07%)
    '     File Size: 1.59 KB


    '     Class DateMetadata
    ' 
    '         Properties: ByteBuffer
    ' 
    '         Function: __assign, EndDateMetadata, (+2 Overloads) GetRootAsDateMetadata
    ' 
    '         Sub: __init, StartDateMetadata
    ' 
    ' 
    ' /********************************************************************************/

#End Region

' automatically generated by the FlatBuffers compiler, do not modify

Imports Microsoft.VisualBasic.DataStorage.FeatherFormat.FlatBuffers

Namespace Impl.FbsMetadata

    Friend Class DateMetadata
        Implements IFlatbufferObject
        Private __p As Table = New Table()
        Public ReadOnly Property ByteBuffer As ByteBuffer Implements IFlatbufferObject.ByteBuffer
            Get
                Return __p.bb
            End Get
        End Property
        Public Shared Function GetRootAsDateMetadata(_bb As ByteBuffer) As DateMetadata
            Return GetRootAsDateMetadata(_bb, New DateMetadata())
        End Function
        Public Shared Function GetRootAsDateMetadata(_bb As ByteBuffer, obj As DateMetadata) As DateMetadata
            Return obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)
        End Function
        Public Sub __init(_i As Integer, _bb As ByteBuffer) Implements IFlatbufferObject.__init
            __p.bb_pos = _i
            __p.bb = _bb
        End Sub
        Public Function __assign(_i As Integer, _bb As ByteBuffer) As DateMetadata
            __init(_i, _bb)
            Return Me
        End Function


        Public Shared Sub StartDateMetadata(builder As FlatBufferBuilder)
            builder.StartObject(0)
        End Sub
        Public Shared Function EndDateMetadata(builder As FlatBufferBuilder) As Offset(Of DateMetadata)
            Dim o As Integer = builder.EndObject()
            Return New Offset(Of DateMetadata)(o)
        End Function
    End Class


End Namespace
