' automatically generated by the FlatBuffers compiler, do not modify

Namespace Impl.FbsMetadata

    Friend Enum Encoding As SByte
        PLAIN = 0
        DICTIONARY = 1
    End Enum


End Namespace
