' automatically generated by the FlatBuffers compiler, do not modify

Imports FlatBuffers

Namespace Impl.Metadata

    Friend Class TimeMetadata
        Implements IFlatbufferObject
        Private __p As Table = New Table()
        Public ReadOnly Property ByteBuffer As ByteBuffer Implements IFlatbufferObject.ByteBuffer
            Get
                Return __p.bb
            End Get
        End Property
        Public Shared Function GetRootAsTimeMetadata(_bb As ByteBuffer) As TimeMetadata
            Return GetRootAsTimeMetadata(_bb, New TimeMetadata())
        End Function
        Public Shared Function GetRootAsTimeMetadata(_bb As ByteBuffer, obj As TimeMetadata) As TimeMetadata
            Return obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)
        End Function
        Public Sub __init(_i As Integer, _bb As ByteBuffer) Implements IFlatbufferObject.__init
            __p.bb_pos = _i
            __p.bb = _bb
        End Sub
        Public Function __assign(_i As Integer, _bb As ByteBuffer) As TimeMetadata
            __init(_i, _bb)
            Return Me
        End Function

        Public ReadOnly Property Unit As TimeUnit
            Get
                Dim o = __p.__offset(4)
                Return If(o <> 0, CType(__p.bb.GetSbyte(o + __p.bb_pos), TimeUnit), TimeUnit.SECOND)
            End Get
        End Property

        Public Shared Function CreateTimeMetadata(builder As FlatBufferBuilder, Optional unit As TimeUnit = TimeUnit.SECOND) As Offset(Of TimeMetadata)
            builder.StartObject(1)
            AddUnit(builder, unit)
            Return EndTimeMetadata(builder)
        End Function

        Public Shared Sub StartTimeMetadata(builder As FlatBufferBuilder)
            builder.StartObject(1)
        End Sub
        Public Shared Sub AddUnit(builder As FlatBufferBuilder, unit As TimeUnit)
            builder.AddSbyte(0, unit, 0)
        End Sub
        Public Shared Function EndTimeMetadata(builder As FlatBufferBuilder) As Offset(Of TimeMetadata)
            Dim o As Integer = builder.EndObject()
            Return New Offset(Of TimeMetadata)(o)
        End Function
    End Class


End Namespace
