' automatically generated by the FlatBuffers compiler, do not modify

Namespace feather.fbs

    Friend Enum TimeUnit As SByte
        SECOND = 0
        MILLISECOND = 1
        MICROSECOND = 2
        NANOSECOND = 3
    End Enum


End Namespace
