' automatically generated by the FlatBuffers compiler, do not modify


Imports FlatBuffers
Imports System

Namespace feather.fbs

    Friend Class TimestampMetadata
        Implements IFlatbufferObject
        Private __p As Table = New Table()
        Public ReadOnly Property ByteBuffer As ByteBuffer Implements IFlatbufferObject.ByteBuffer
            Get
                Return __p.bb
            End Get
        End Property
        Public Shared Function GetRootAsTimestampMetadata(_bb As ByteBuffer) As TimestampMetadata
            Return GetRootAsTimestampMetadata(_bb, New TimestampMetadata())
        End Function
        Public Shared Function GetRootAsTimestampMetadata(_bb As ByteBuffer, obj As TimestampMetadata) As TimestampMetadata
            Return obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)
        End Function
        Public Sub __init(_i As Integer, _bb As ByteBuffer) Implements IFlatbufferObject.__init
            __p.bb_pos = _i
            __p.bb = _bb
        End Sub
        Public Function __assign(_i As Integer, _bb As ByteBuffer) As TimestampMetadata
            __init(_i, _bb)
            Return Me
        End Function

        Public ReadOnly Property Unit As TimeUnit
            Get
                Dim o = __p.__offset(4)
                Return If(o <> 0, CType(__p.bb.GetSbyte(o + __p.bb_pos), TimeUnit), TimeUnit.SECOND)
            End Get
        End Property
        ''' Timestamp data is assumed to be UTC, but the time zone is stored here for
        ''' presentation as localized
        Public ReadOnly Property Timezone As String
            Get
                Dim o = __p.__offset(6)
                Return If(o <> 0, __p.__string(o + __p.bb_pos), Nothing)
            End Get
        End Property
        Public Function GetTimezoneBytes() As ArraySegment(Of Byte)?
            Return __p.__vector_as_arraysegment(6)
        End Function

        Public Shared Function CreateTimestampMetadata(builder As FlatBufferBuilder, Optional unit As TimeUnit = TimeUnit.SECOND, Optional timezoneOffset As StringOffset = Nothing) As Offset(Of TimestampMetadata)
            builder.StartObject(2)
            AddTimezone(builder, timezoneOffset)
            AddUnit(builder, unit)
            Return EndTimestampMetadata(builder)
        End Function

        Public Shared Sub StartTimestampMetadata(builder As FlatBufferBuilder)
            builder.StartObject(2)
        End Sub
        Public Shared Sub AddUnit(builder As FlatBufferBuilder, unit As TimeUnit)
            builder.AddSbyte(0, unit, 0)
        End Sub
        Public Shared Sub AddTimezone(builder As FlatBufferBuilder, timezoneOffset As StringOffset)
            builder.AddOffset(1, timezoneOffset.Value, 0)
        End Sub
        Public Shared Function EndTimestampMetadata(builder As FlatBufferBuilder) As Offset(Of TimestampMetadata)
            Dim o As Integer = builder.EndObject()
            Return New Offset(Of TimestampMetadata)(o)
        End Function
    End Class


End Namespace
