' automatically generated by the FlatBuffers compiler, do not modify

Namespace Impl.FbsMetadata

    Friend Enum Type As SByte
        BOOL = 0
        INT8 = 1
        INT16 = 2
        INT32 = 3
        INT64 = 4
        UINT8 = 5
        UINT16 = 6
        UINT32 = 7
        UINT64 = 8
        FLOAT = 9
        [DOUBLE] = 10
        UTF8 = 11
        BINARY = 12
        CATEGORY = 13
        TIMESTAMP = 14
        [DATE] = 15
        TIME = 16
    End Enum


End Namespace
