#Region "Microsoft.VisualBasic::59d017cd9c9a541c087e8847d51f5945, Data\BinaryData\Feather\Impl\Metadata\Type.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 26
    '    Code Lines: 21
    ' Comment Lines: 1
    '   Blank Lines: 4
    '     File Size: 505 B


    '     Enum Type
    ' 
    ' 
    '  
    ' 
    ' 
    ' 
    ' 
    ' /********************************************************************************/

#End Region

' automatically generated by the FlatBuffers compiler, do not modify

Namespace Impl.FbsMetadata

    Friend Enum Type As SByte
        BOOL = 0
        INT8 = 1
        INT16 = 2
        INT32 = 3
        INT64 = 4
        UINT8 = 5
        UINT16 = 6
        UINT32 = 7
        UINT64 = 8
        FLOAT = 9
        [DOUBLE] = 10
        UTF8 = 11
        BINARY = 12
        CATEGORY = 13
        TIMESTAMP = 14
        [DATE] = 15
        TIME = 16
    End Enum


End Namespace
