' automatically generated by the FlatBuffers compiler, do not modify

Namespace feather.fbs

    Friend Enum TypeMetadata As Byte
        NONE = 0
        CategoryMetadata = 1
        TimestampMetadata = 2
        DateMetadata = 3
        TimeMetadata = 4
    End Enum


End Namespace
