<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <StartupObject>test.Module1</StartupObject>
    <RootNamespace>test</RootNamespace>

    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <Version>1.0.9753.4776</Version>
    <AssemblyVersion>1.0.9753.4776</AssemblyVersion>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Data\BinaryData\BinaryData\binarydata-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\Data_science\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\MPEG4\MPEG4.vbproj" />
    <ProjectReference Include="..\AVI.NET5.vbproj" />
  </ItemGroup>
 </Project>