<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Microsoft.VisualBasic.Data.MyersDiff</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Microsoft.VisualBasic.Data.MyersDiff</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <Version>1.0.9742.7537</Version>
    <AssemblyVersion>1.0.9742.7537</AssemblyVersion>
    <Configurations>nuget_release</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='nuget_release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>../../.nuget/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="test\**" />
    <EmbeddedResource Remove="test\**" />
    <None Remove="test\**" />
  </ItemGroup>

</Project>
