<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Microsoft.VisualBasic.Computing.ILCuda</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AssemblyName>Microsoft.VisualBasic.Computing.ILCuda.GPUTensor</AssemblyName>
  </PropertyGroup>

</Project>
