#Region "Microsoft.VisualBasic::0adad75b7efa70e95bbb85d67786cb8c, Microsoft.VisualBasic.Core\src\ApplicationServices\Terminal\Utility\UnixMan\UnixManPage.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 163
    '    Code Lines: 98
    ' Comment Lines: 46
    '   Blank Lines: 19
    '     File Size: 6.08 KB


    '     Class Index
    ' 
    '         Properties: [date], category, index, keyword, title
    ' 
    '         Function: ToString
    ' 
    '     Class UnixManPage
    ' 
    '         Properties: AUTHOR, BUGS, COPYRIGHT, DESCRIPTION, DETAILS
    '                     EXAMPLES, EXIT_STATUS, FILES, HISTORY, index
    '                     LICENSE, NAME, OPTIONS, PROLOG, SEE_ALSO
    '                     SYNOPSIS, VALUE, WARRANTY
    ' 
    '         Function: (+2 Overloads) ToString
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports System.Text
Imports Microsoft.VisualBasic.ComponentModel.DataSourceModel
Imports Microsoft.VisualBasic.Linq

Namespace ApplicationServices.Terminal.Utility

    ''' <summary>
    ''' the document index
    ''' </summary>
    Public Class Index

        Public Property index As String
        Public Property category As Integer
        Public Property [date] As Date = Now
        Public Property keyword As String
        Public Property title As String

        Public Overrides Function ToString() As String
            Return $".TH {Strings.UCase(index)} {category} {[date].ToString("yyyy-MMM")} ""{keyword}"" ""{title}"""
        End Function

    End Class

    ''' <summary>
    ''' man手册页（manual pages，“手册”），是类UNIX系统最重要的手册工具。多数类UNIX都预装了它，这也包括Arch。使用man手册页的命令是：man。
    ''' </summary>
    Public Class UnixManPage

        Public Property index As Index

        Public Property PROLOG As String

        ''' <summary>
        ''' 手册叙述对象名称，及简要描述。
        ''' </summary>
        ''' <returns></returns>
        Public Property NAME As String
        ''' <summary>
        ''' 命令参数格式，或者函数调用格式等。
        ''' </summary>
        ''' <returns></returns>
        Public Property SYNOPSIS As String
        ''' <summary>
        ''' 对叙述对象更加详细的描述。
        ''' </summary>
        ''' <returns></returns>
        Public Property DESCRIPTION As String
        Public Property VALUE As String
        Public Property DETAILS As String
        ''' <summary>
        ''' 由浅入深的使用示例。
        ''' </summary>
        ''' <returns></returns>
        Public Property EXAMPLES As String
        ''' <summary>
        ''' 命令行或者函数调用参数的意义。
        ''' </summary>
        ''' <returns></returns>
        Public Property OPTIONS As NamedValue(Of String)()
        ''' <summary>
        ''' 不同返回（退出）代码的含义。
        ''' </summary>
        ''' <returns></returns>
        Public Property EXIT_STATUS As String
        ''' <summary>
        ''' 与叙述对象相关的文件。
        ''' </summary>
        ''' <returns></returns>
        Public Property FILES As String
        ''' <summary>
        ''' 已知的bug。
        ''' </summary>
        ''' <returns></returns>
        Public Property BUGS As String
        ''' <summary>
        ''' 相关内容列表。
        ''' </summary>
        ''' <returns></returns>
        Public Property SEE_ALSO As String
        Public Property AUTHOR As String
        Public Property HISTORY As String
        Public Property COPYRIGHT As String
        Public Property LICENSE As String
        Public Property WARRANTY As String

        ''' <summary>
        ''' 生成man page的文本内容
        ''' </summary>
        ''' <returns></returns>
        Public Overrides Function ToString() As String
            Return ToString(Me, Nothing)
        End Function

        Public Overloads Shared Function ToString(man As UnixManPage, Optional comments$ = "DO NOT MODIFY THIS FILE! It was generated by sciBASIC.NET tools.") As String
            Dim text As New StringBuilder

            If Not comments.StringEmpty Then
                For Each line As String In comments.LineTokens
                    Call text.AppendLine($".\"" {line}")
                Next
            End If

            Call text.AppendLine(man.index.ToString)
            Call text.AppendLine(".SH NAME")
            Call text.AppendLine($"{man.NAME} \- {man.PROLOG}")

            If Not man.SYNOPSIS.StringEmpty Then
                Call text.AppendLine(".SH SYNOPSIS")
                Call text.AppendLine($"\fI{man.SYNOPSIS}\fR")
            End If
            If Not man.DESCRIPTION.StringEmpty Then
                Call text.AppendLine(".SH DESCRIPTION")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.DESCRIPTION)
                Call text.AppendLine(".PP")
            End If

            If Not man.OPTIONS.IsNullOrEmpty Then
                Call text.AppendLine(".SH OPTIONS")

                For Each opt As NamedValue(Of String) In man.OPTIONS.SafeQuery
                    Call text.AppendLine(".PP")
                    Call text.AppendLine($"\fB{opt.Name}\fB \fR\- {opt.Value}. {opt.Description}")
                    Call text.AppendLine(".PP")
                Next
            End If

            If Not man.VALUE.StringEmpty Then
                Call text.AppendLine(".SH VALUE")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.VALUE)
                Call text.AppendLine(".PP")
            End If

            If Not man.DETAILS.StringEmpty Then
                Call text.AppendLine(".SH DETAILS")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.DETAILS)
                Call text.AppendLine(".PP")
            End If
            If Not man.SEE_ALSO.StringEmpty Then
                Call text.AppendLine(".SH SEE ALSO")
                Call text.AppendLine(man.SEE_ALSO)
            End If
            If Not man.FILES.StringEmpty Then
                Call text.AppendLine(".SH FILES")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.FILES)
                Call text.AppendLine(".PP")
            End If
            If Not man.AUTHOR.StringEmpty Then
                Call text.AppendLine(".SH AUTHOR")
                Call text.AppendLine($"Written by \fB{man.AUTHOR.Replace("-", "\-")}\fR")
            End If
            If Not man.COPYRIGHT.StringEmpty Then
                Call text.AppendLine(".SH COPYRIGHT")
                Call text.AppendLine(man.COPYRIGHT)
            End If

            Return text.ToString
        End Function
    End Class
End Namespace
