<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>test</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\mime\application%json\JSON-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\mime\application%xml\xml-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\mime\text%html\html_netcore5.vbproj" />
    <ProjectReference Include="..\GraphQuery.NET5.vbproj" />
  </ItemGroup>

</Project>
