<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Microsoft.VisualBasic.Data.NLP.Knowledge</RootNamespace>
    <AssemblyName>Microsoft.VisualBasic.Data.NLP.Knowledge</AssemblyName>
    <OptionExplicit>On</OptionExplicit>
    <OptionStrict>Off</OptionStrict>
    <Import>Microsoft.VisualBasic</Import>
    <Import>System</Import>
    <Import>System.Collections.Generic</Import>
    <Import>System.Linq</Import>
    <Platforms>AnyCPU;x64</Platforms>
    <Version>1.0.9742.6623</Version>
    <AssemblyVersion>1.0.9742.6623</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="test\**" />
    <EmbeddedResource Remove="test\**" />
    <None Remove="test\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data_science\Graph\graph-netcore5.vbproj" />
    <ProjectReference Include="..\..\Data_science\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
  </ItemGroup>

</Project>
