<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VBScriptHost</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyTitle>VisualBasic.NET Scripting Host</AssemblyTitle>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyName>vbs</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <OutputPath>../../.nuget/</OutputPath>
    <LangVersion>16</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="5.9.0" />
    <PackageReference Include="SkiaSharp" Version="4.152.0" />
    <PackageReference Include="SkiaSharp.Extended" Version="3.0.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.152.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.152.0" />
    <PackageReference Include="SkiaSharp.Svg" Version="1.60.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\dev\VisualStudio\VisualStudio.NET5.vbproj" />
  </ItemGroup>

</Project>
