Imports Microsoft.VisualBasic.ComponentModel.DataSourceModel
Imports Microsoft.VisualBasic.Linq
Imports System.Text

Namespace ApplicationServices.Terminal.Utility

    Module ManWriter

        Public Const default_comment_text As String = "DO NOT MODIFY THIS FILE! It was generated by sciBASIC.NET tools."

        Public Function ToString(man As UnixManPage, comments$) As String
            Dim text As New StringBuilder

            If Not comments.StringEmpty Then
                For Each line As String In comments.LineTokens
                    Call text.AppendLine($".\"" {line}")
                Next
            End If

            Call text.AppendLine(man.index.ToString)
            Call text.AppendLine(".SH NAME")
            Call text.AppendLine($"{man.NAME} \- {man.PROLOG}")

            If Not man.SYNOPSIS.StringEmpty Then
                Call text.AppendLine(".SH SYNOPSIS")
                Call text.AppendLine($"\fI{man.SYNOPSIS}\fR")
            End If
            If Not man.DESCRIPTION.StringEmpty Then
                Call text.AppendLine(".SH DESCRIPTION")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.DESCRIPTION)
                Call text.AppendLine(".PP")
            End If

            If Not man.OPTIONS.IsNullOrEmpty Then
                Call text.AppendLine(".SH OPTIONS")

                For Each opt As NamedValue(Of String) In man.OPTIONS.SafeQuery
                    Call text.AppendLine(".PP")
                    Call text.AppendLine($"\fB{opt.Name}\fB \fR\- {opt.Value}. {opt.Description}")
                    Call text.AppendLine(".PP")
                Next
            End If

            If Not man.VALUE.StringEmpty Then
                Call text.AppendLine(".SH VALUE")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.VALUE)
                Call text.AppendLine(".PP")
            End If

            If Not man.DETAILS.StringEmpty Then
                Call text.AppendLine(".SH DETAILS")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.DETAILS)
                Call text.AppendLine(".PP")
            End If
            If Not man.SEE_ALSO.StringEmpty Then
                Call text.AppendLine(".SH SEE ALSO")
                Call text.AppendLine(man.SEE_ALSO)
            End If
            If Not man.FILES.StringEmpty Then
                Call text.AppendLine(".SH FILES")
                Call text.AppendLine(".PP")
                Call text.AppendLine(man.FILES)
                Call text.AppendLine(".PP")
            End If
            If Not man.AUTHOR.StringEmpty Then
                Call text.AppendLine(".SH AUTHOR")
                Call text.AppendLine($"Written by \fB{man.AUTHOR.Replace("-", "\-")}\fR")
            End If
            If Not man.COPYRIGHT.StringEmpty Then
                Call text.AppendLine(".SH COPYRIGHT")
                Call text.AppendLine(man.COPYRIGHT)
            End If

            Return text.ToString
        End Function
    End Module
End Namespace