#Region "Microsoft.VisualBasic::f3da1004a03641eae52108801fa6abe9, Microsoft.VisualBasic.Core\src\ApplicationServices\Terminal\Utility\UnixMan\ManFile\ManWriter.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 71
    '    Code Lines: 55 (77.46%)
    ' Comment Lines: 0 (0.00%)
    '    - Xml Docs: 0.00%
    ' 
    '   Blank Lines: 16 (22.54%)
    '     File Size: 2.88 KB


    '     Module ManWriter
    ' 
    '         Function: ToString
    ' 
    '         Sub: WriteTextBlock
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports Microsoft.VisualBasic.ComponentModel.DataSourceModel
Imports Microsoft.VisualBasic.Linq
Imports System.Text

Namespace ApplicationServices.Terminal.Utility

    Module ManWriter

        Public Const default_comment_text As String = "DO NOT MODIFY THIS FILE! It was generated by sciBASIC.NET tools."

        Public Function ToString(man As UnixManPage, comments$) As String
            Dim text As New StringBuilder

            If Not comments.StringEmpty Then
                For Each line As String In comments.LineTokens
                    Call text.AppendLine($".\"" {line}")
                Next
            End If

            Call text.AppendLine(man.index.ToString)
            Call text.AppendLine(".SH NAME")
            Call text.AppendLine($"{man.NAME} \- {man.PROLOG}")

            If Not man.SYNOPSIS.StringEmpty Then
                Call text.AppendLine(".SH SYNOPSIS")
                Call text.AppendLine($"\fI{man.SYNOPSIS}\fR")
            End If

            If Not man.DESCRIPTION.StringEmpty Then Call WriteTextBlock(text, "DESCRIPTION", man.DESCRIPTION)

            If Not man.OPTIONS.IsNullOrEmpty Then
                Call text.AppendLine(".SH OPTIONS")

                For Each opt As NamedValue(Of String) In man.OPTIONS.SafeQuery
                    Call text.AppendLine(".PP")
                    Call text.AppendLine($"\fB{opt.Name}\fB \fR\- {opt.Value}. {opt.Description}")
                    Call text.AppendLine(".PP")
                Next
            End If

            If Not man.VALUE.StringEmpty Then Call WriteTextBlock(text, "VALUE", man.VALUE)
            If Not man.DETAILS.StringEmpty Then Call WriteTextBlock(text, "DETAILS", man.DETAILS)
            If Not man.EXAMPLES.StringEmpty Then Call WriteTextBlock(text, "EXAMPLES", man.EXAMPLES)

            If Not man.SEE_ALSO.StringEmpty Then
                Call text.AppendLine(".SH SEE ALSO")
                Call text.AppendLine(man.SEE_ALSO)
            End If

            If Not man.FILES.StringEmpty Then Call WriteTextBlock(text, "FILES", man.FILES)

            If Not man.AUTHOR.StringEmpty Then
                Call text.AppendLine(".SH AUTHOR")
                Call text.AppendLine($"Written by \fB{man.AUTHOR.Replace("-", "\-")}\fR")
            End If
            If Not man.COPYRIGHT.StringEmpty Then
                Call text.AppendLine(".SH COPYRIGHT")
                Call text.AppendLine(man.COPYRIGHT)
            End If

            Return text.ToString
        End Function

        Private Sub WriteTextBlock(text As StringBuilder, title As String, str As String)
            Call text.AppendLine($".SH {title}")
            Call text.AppendLine($".PP")
            Call text.AppendLine(str)
            Call text.AppendLine($".PP")
        End Sub
    End Module
End Namespace
