'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.VisualBasic.Math.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 0000   1.276- 1.218-   .453-  .350-   .723   .676   1.099-  .314-   .394-  .633-
        '''0001    .318-  .799-  1.664- 1.391    .382   .733    .653   .219    .681- 1.129 
        '''0002   1.377- 1.257-   .495   .139-   .854-  .428   1.322-  .315-   .732- 1.348-
        '''0003   2.334   .337-  1.955-  .636-  1.318-  .433-   .545   .428    .297-  .276 
        '''0004   1.136-  .642   3.436  1.667-   .847  1.173-   .355-  .035    .359   .930 
        '''0005    .414   .011-   .666  1.132-   .410- 1.077-   .734  1.484    .340-  .789 
        '''0006    .494-  .364  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property deviates() As String
            Get
                Return ResourceManager.GetString("deviates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 00000   10097 32533  76520 13586  34673 54876  80959 09117  39292 74945
        '''00001   37542 04805  64894 74296  24805 24037  20636 10402  00822 91665
        '''00002   08422 68953  19645 09303  23209 02560  15953 34764  35080 33606
        '''00003   99019 02529  09376 70715  38311 31165  88676 74397  04436 27659
        '''00004   12807 99970  80157 36147  64032 36653  98951 16877  12171 76833
        '''00005   66065 74717  34072 76850  36697 36170  65813 39885  11199 29170
        '''00006   31060 10805  45571 82406  35303 42614  86799 07439  23403 09732
        '''0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property digits() As String
            Get
                Return ResourceManager.GetString("digits", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
