#Region "Microsoft.VisualBasic::65a747f564bb5e081974d67c1d674644, Data_science\Mathematica\Math\Randomizer\My Project\Resources.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 94
    '    Code Lines: 42
    ' Comment Lines: 42
    '   Blank Lines: 10
    '     File Size: 4.65 KB


    '     Module Resources
    ' 
    '         Properties: Culture, deviates, digits, ResourceManager
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.VisualBasic.Math.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000   1.276- 1.218-   .453-  .350-   .723   .676   1.099-  .314-   .394-  .633-
        '''0001    .318-  .799-  1.664- 1.391    .382   .733    .653   .219    .681- 1.129 
        '''0002   1.377- 1.257-   .495   .139-   .854-  .428   1.322-  .315-   .732- 1.348-
        '''0003   2.334   .337-  1.955-  .636-  1.318-  .433-   .545   .428    .297-  .276 
        '''0004   1.136-  .642   3.436  1.667-   .847  1.173-   .355-  .035    .359   .930 
        '''0005    .414   .011-   .666  1.132-   .410- 1.077-   .734  1.484    .340-  .789 
        '''0006    .494-  .364   1.23 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property deviates() As String
            Get
                Return ResourceManager.GetString("deviates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 00000   10097 32533  76520 13586  34673 54876  80959 09117  39292 74945
        '''00001   37542 04805  64894 74296  24805 24037  20636 10402  00822 91665
        '''00002   08422 68953  19645 09303  23209 02560  15953 34764  35080 33606
        '''00003   99019 02529  09376 70715  38311 31165  88676 74397  04436 27659
        '''00004   12807 99970  80157 36147  64032 36653  98951 16877  12171 76833
        '''00005   66065 74717  34072 76850  36697 36170  65813 39885  11199 29170
        '''00006   31060 10805  45571 82406  35303 42614  86799 07439  23403 09732
        '''00007    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property digits() As String
            Get
                Return ResourceManager.GetString("digits", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
