<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
   
    <OutputType>Exe</OutputType>
    <StartupObject>GAF_test2.Program</StartupObject>
    <RootNamespace>GAF_test2</RootNamespace>
    <AssemblyName>GAF_test2</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Configurations>Debug;Release;LipidSearch;Rsharp_app_release;mzkit;mzkit_win32;gcmodeller_desktop;nuget_release;MEMI-Desktop</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Data\DataFrame\dataframework-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\gr\Microsoft.VisualBasic.Imaging\imaging.NET5.vbproj" />
    <ProjectReference Include="..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\mime\text%html\html_netcore5.vbproj" />
    <ProjectReference Include="..\..\..\nlp\NLP\NLP.NET.vbproj" />
    <ProjectReference Include="..\..\DataMining\DataMining\DataMining.NET5.vbproj" />
    <ProjectReference Include="..\..\MachineLearning\MachineLearning\machine_learning-netcore5.vbproj" />
    <ProjectReference Include="..\..\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\Mathematica\Math\ODESolver.Extensions\ODESolver.Extensions.NET5.vbproj" />
    <ProjectReference Include="..\..\Mathematica\Math\ODE\odes-netcore5.vbproj" />
    <ProjectReference Include="..\..\Visualization\DataPlot\DataPlot.vbproj" />
  </ItemGroup>
 
</Project>