#Region "Microsoft.VisualBasic::5011ad252e421a063341e4589cfddcda, Microsoft.VisualBasic.Core\src\ComponentModel\File\XmlAssembly\DigitalSignature.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 85
    '    Code Lines: 52 (61.18%)
    ' Comment Lines: 20 (23.53%)
    '    - Xml Docs: 95.00%
    ' 
    '   Blank Lines: 13 (15.29%)
    '     File Size: 2.82 KB


    '     Class DigitalSignature
    ' 
    '         Constructor: (+1 Overloads) Sub New
    '         Function: (+2 Overloads) GetModelInfo, Parse
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports System.Runtime.CompilerServices
Imports Microsoft.VisualBasic.ComponentModel.DataSourceModel
Imports Microsoft.VisualBasic.Scripting.MetaData

Namespace ComponentModel

    ''' <summary>
    ''' helper for parse the .NET CLR type metadata 
    ''' inside a xml file content which is generated 
    ''' by <see cref="XmlDataModel"/>
    ''' </summary>
    Public Class DigitalSignature

        ReadOnly source As IEnumerable(Of String)

        Dim modelType As String = Nothing
        Dim assembly As String = Nothing
        Dim doParse As Boolean = False
        Dim info As TypeInfo

        ''' <summary>
        ''' the file path or the xml file content text
        ''' </summary>
        ''' <param name="file"></param>
        Sub New(file As String)
            source = file.SolveStream.LineTokens
        End Sub

        Private Function Parse(line As String) As Boolean
            Dim tag As NamedValue(Of String) = line.GetTagValue(":", trim:=True)

            If tag.Name = "model" Then
                modelType = tag.Value
            ElseIf tag.Name = "assembly" Then
                assembly = tag.Value
            End If

            If (Not modelType.StringEmpty) AndAlso (Not assembly.StringEmpty) Then
                info = New TypeInfo With {
                    .assembly = assembly.StringSplit(",\s+")(Scan0) & ".dll",
                    .fullName = modelType,
                    .reference = assembly
                }

                Return True
            Else
                Return False
            End If
        End Function

        ''' <summary>
        ''' parse xml assembly type reference which is generated 
        ''' by <see cref="XmlDataModel"/>
        ''' </summary>
        ''' <returns></returns>
        Public Function GetModelInfo() As TypeInfo
            For Each line As String In source
                line = Strings.Trim(line)

                If line = "<!--" Then
                    doParse = True
                ElseIf doParse Then
                    If Parse(line) Then
                        Return info
                    End If
                ElseIf line = "-->" Then
                    Exit For
                End If
            Next

            Return Nothing
        End Function

        ''' <summary>
        ''' parse xml assembly type reference which is generated by <see cref="XmlDataModel"/>
        ''' </summary>
        ''' <param name="file"></param>
        ''' <returns></returns>
        ''' 
        <MethodImpl(MethodImplOptions.AggressiveInlining)>
        Public Shared Function GetModelInfo(file As String) As TypeInfo
            Return New DigitalSignature(file).GetModelInfo
        End Function
    End Class
End Namespace
