<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>test</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\application%json\JSON-netcore5.vbproj" />
    <ProjectReference Include="..\..\text%markdown\markdown.NET5.vbproj" />
    <ProjectReference Include="..\docx\WordDocument.vbproj" />
  </ItemGroup>

</Project>
