#Region "Microsoft.VisualBasic::0b66649c7e03eb9480d133565a9b1788, Data_science\MachineLearning\MachineLearning\ComponentModel\Status0.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 160
    '    Code Lines: 50 (31.25%)
    ' Comment Lines: 93 (58.13%)
    '    - Xml Docs: 100.00%
    ' 
    '   Blank Lines: 17 (10.62%)
    '     File Size: 6.50 KB


    '     Class Status0
    ' 
    '         Function: GetFloats, GetVector
    ' 
    '     Class ConstantStatus0
    ' 
    '         Properties: C
    ' 
    '         Function: GetInitialValue, ToString
    ' 
    '     Class RandomStatus0
    ' 
    '         Properties: Max, Min
    ' 
    '         Constructor: (+2 Overloads) Sub New
    '         Function: GetInitialValue, ToString
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports System.Runtime.CompilerServices
Imports System.Xml.Serialization
Imports Microsoft.VisualBasic.Math.LinearAlgebra
Imports randf = Microsoft.VisualBasic.Math.RandomExtensions

Namespace ComponentModel

    ''' <summary>
    ''' The abstract model of the initial value generator of the network node status.
    ''' </summary>
    ''' <remarks>
    ''' This abstract model is usually used for generates the initial value of the
    ''' weight vector or the bias value of the neuron node in a neural network, or
    ''' the initial value of the parameter vector in a general machine learning model.
    ''' </remarks>
    Public MustInherit Class Status0

        ''' <summary>
        ''' Produce one single initial value.
        ''' </summary>
        ''' <returns>
        ''' A <see cref="Single"/> value which is generated from the specific 
        ''' initial value strategy that implemented in the derived class.
        ''' </returns>
        Public MustOverride Function GetInitialValue() As Single

        ''' <summary>
        ''' Produce a vector of the initial values with a given dimension size.
        ''' </summary>
        ''' <param name="dims">The dimension size of the target vector.</param>
        ''' <returns>
        ''' A <see cref="Vector"/> which its elements are produced by the 
        ''' <see cref="GetInitialValue"/> function.
        ''' </returns>
        <MethodImpl(MethodImplOptions.AggressiveInlining)>
        Public Function GetVector(dims As Integer) As Vector
            Return New Vector(GetFloats(count:=dims))
        End Function

        ''' <summary>
        ''' Produce a sequence of the initial values.
        ''' </summary>
        ''' <param name="count">How many initial values should be generated?</param>
        ''' <returns>
        ''' A lazy evaluated sequence of <see cref="Single"/> values, each element 
        ''' is generated by the <see cref="GetInitialValue"/> function.
        ''' </returns>
        Public Iterator Function GetFloats(count As Integer) As IEnumerable(Of Single)
            For i As Integer = 0 To count - 1
                Yield GetInitialValue()
            Next
        End Function

        ''' <summary>
        ''' Convert the initial value generator model as a single initial value 
        ''' via the <see cref="GetInitialValue"/> function.
        ''' </summary>
        ''' <param name="a">A initial value generator model.</param>
        ''' <returns>A <see cref="Single"/> value which is generated from the given generator model.</returns>
        <MethodImpl(MethodImplOptions.AggressiveInlining)>
        Public Shared Narrowing Operator CType(a As Status0) As Single
            Return a.GetInitialValue
        End Operator

    End Class

    ''' <summary>
    ''' A constant value as the initial value generator: the <see cref="C"/> 
    ''' value will always be generated.
    ''' </summary>
    ''' <remarks>
    ''' This initial value strategy is usually used for generate the initial 
    ''' bias value of the neuron node, example as constant zero.
    ''' </remarks>
    Public Class ConstantStatus0 : Inherits Status0

        ''' <summary>
        ''' The constant initial value.
        ''' </summary>
        ''' <returns>A <see cref="Single"/> constant value.</returns>
        <XmlText>
        Public Property C As Single

        ''' <summary>
        ''' Always returns the constant value <see cref="C"/>.
        ''' </summary>
        ''' <returns>The <see cref="C"/> constant value.</returns>
        <MethodImpl(MethodImplOptions.AggressiveInlining)>
        Public Overrides Function GetInitialValue() As Single
            Return C
        End Function

        ''' <summary>
        ''' Display the constant value in string format.
        ''' </summary>
        ''' <returns>The string text value of the <see cref="C"/> constant.</returns>
        Public Overrides Function ToString() As String
            Return C.ToString
        End Function
    End Class

    ''' <summary>
    ''' Generate the initial value from a uniform random distribution: the value 
    ''' is sampled from the interval between <see cref="Min"/> and <see cref="Max"/>.
    ''' </summary>
    ''' <remarks>
    ''' Random initialization is essential for breaking the symmetry of the neuron 
    ''' nodes in the same layer of a neural network.
    ''' </remarks>
    Public Class RandomStatus0 : Inherits Status0

        ''' <summary>
        ''' The lower bound of the random sampling interval.
        ''' </summary>
        ''' <returns>A <see cref="Double"/> value.</returns>
        <XmlAttribute> Public Property Min As Double
        ''' <summary>
        ''' The upper bound of the random sampling interval.
        ''' </summary>
        ''' <returns>A <see cref="Double"/> value.</returns>
        <XmlAttribute> Public Property Max As Double

        ''' <summary>
        ''' Create a random initial value generator with the default interval [0, 1].
        ''' </summary>
        Sub New()
        End Sub

        ''' <summary>
        ''' Create a random initial value generator with a specific sampling interval.
        ''' </summary>
        ''' <param name="min">The lower bound of the random sampling interval.</param>
        ''' <param name="max">The upper bound of the random sampling interval.</param>
        Sub New(min As Double, max As Double)
            Me.Min = min
            Me.Max = max
        End Sub

        ''' <summary>
        ''' Sample one random value from the uniform distribution on 
        ''' the interval [<see cref="Min"/>, <see cref="Max"/>].
        ''' </summary>
        ''' <returns>A random <see cref="Single"/> value.</returns>
        <MethodImpl(MethodImplOptions.AggressiveInlining)>
        Public Overrides Function GetInitialValue() As Single
            Return randf.NextDouble(Min, Max)
        End Function

        ''' <summary>
        ''' Display the sampling interval in string format.
        ''' </summary>
        ''' <returns>
        ''' A string in format like ``randf(min, max) = value``, in which the value 
        ''' is a freshly sampled random number.
        ''' </returns>
        Public Overrides Function ToString() As String
            Return $"randf({Min}, {Max}) = {GetInitialValue()}"
        End Function
    End Class
End Namespace
