'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.VisualBasic.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property bashRunner() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bashRunner", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ?&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;The Code Project Open License (CPOL)&lt;/title&gt;
        '''&lt;Style&gt;
        '''BODY, P, TD { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10pt }
        '''H1,H2,H3,H4,H5 { color: #ff9900; font-weight: bold; }
        '''H1 { font-size: 14pt;color:black }
        '''H2 { font-size: 13pt; }
        '''H3 { font-size: 12pt; }
        '''H4 { font-size: 10pt; color: black; }
        '''PRE { BACKGROUND-COLOR: #FBEDBB; FONT-FAMILY: &quot;Courier New&quot;, Courier, mono; WHITE-SPACE: pre; }
        '''CODE { COLOR: #990000; FONT-FAMILY: &quot;Courier New&quot;, Courier, mono; }
        '''.S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CPOL() As String
            Get
                Return ResourceManager.GetString("CPOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''to [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property gpl() As String
            Get
                Return ResourceManager.GetString("gpl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property help() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This program is free software: you can redistribute it and/or modify
        '''it under the terms of the GNU General Public License as published by
        '''the Free Software Foundation, either version 3 of the License, or
        '''any later version.
        '''
        '''This program is distributed in the hope that it will be useful,
        '''but WITHOUT ANY WARRANTY; without even the implied warranty of
        '''MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        '''GNU General Public License for more details.
        '''
        '''You should have received a copy of the GNU  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property license() As String
            Get
                Return ResourceManager.GetString("license", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Name	MIME Type / Internet Media Type	File Extension	More Details
        '''3D Crossword Plugin	application/vnd.hzn-3d-crossword	.x3d	IANA: 3D Crossword Plugin
        '''3GP	video/3gpp	.3gp	Wikipedia: 3GP
        '''3GP2	video/3gpp2	.3g2	Wikipedia: 3G2
        '''3GPP MSEQ File	application/vnd.mseq	.mseq	IANA: 3GPP MSEQ File
        '''3M Post It Notes	application/vnd.3m.post-it-notes	.pwn	IANA: 3M Post It Notes
        '''3rd Generation Partnership Project - Pic Large	application/vnd.3gpp.pic-bw-large	.plb	3GPP
        '''3rd Generation Partnership Project - Pic Small	appli [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property List_of_MIME_types___Internet_Media_Types_() As String
            Get
                Return ResourceManager.GetString("List_of_MIME_types___Internet_Media_Types_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property runMono() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("runMono", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
