#Region "Microsoft.VisualBasic::8422160e74aebb74095bee4b4015c1f5, Data_science\MachineLearning\MachineLearning\Darwinism\GeneticAlgorithm\Population\Substitution\ReplacementStrategy.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 31
    '    Code Lines: 23 (74.19%)
    ' Comment Lines: 3 (9.68%)
    '    - Xml Docs: 100.00%
    ' 
    '   Blank Lines: 5 (16.13%)
    '     File Size: 1.11 KB


    '     Interface IStrategy
    ' 
    '         Properties: type
    ' 
    '         Function: newPopulation
    ' 
    '     Enum Strategies
    ' 
    '         EliteCrossbreed, Naive
    ' 
    '  
    ' 
    ' 
    ' 
    '     Module Extensions
    ' 
    '         Function: GetStrategy
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports System.Runtime.CompilerServices
Imports Microsoft.VisualBasic.MachineLearning.Darwinism.Models

Namespace Darwinism.GAF.Population.SubstitutionStrategy

    ''' <summary>
    ''' The interface of the population substitution strategies: it decides how 
    ''' the new individuals replace the old ones and therefore controls the 
    ''' convergence speed and the diversity of the genetic algorithm.
    ''' </summary>
    ''' <typeparam name="Chr">The chromosome type of the genetic algorithm.</typeparam>
    Public Interface IStrategy(Of Chr As {Class, Chromosome(Of Chr)})
        ''' <summary>
        ''' The <see cref="Strategies"/> value which identifies the current 
        ''' substitution strategy.
        ''' </summary>
        ReadOnly Property type As Strategies
        ''' <summary>
        ''' Produce the population of the next generation.
        ''' </summary>
        ''' <param name="newPop">The new population which contains the offspring individuals.</param>
        ''' <param name="GA">The genetic algorithm driver of the current evolution process.</param>
        ''' <returns>The population which will be used by the next generation.</returns>
        Function newPopulation(newPop As Population(Of Chr), GA As GeneticAlgorithm(Of Chr)) As Population(Of Chr)
    End Interface

    ''' <summary>
    ''' enums of the population substitution strategies
    ''' </summary>
    Public Enum Strategies
        ''' <summary>
        ''' The naive strategy: sort the population by fitness and then trim the 
        ''' population, which is implemented by the <see cref="SimpleReplacement(Of Chr)"/>.
        ''' </summary>
        Naive
        ''' <summary>
        ''' The elite crossbreed strategy: only the elite individuals are kept 
        ''' and the remaining population members are generated by the crossover 
        ''' between these elite individuals, which is implemented by the 
        ''' <see cref="EliteReplacement(Of Chr)"/>.
        ''' </summary>
        EliteCrossbreed
    End Enum

    <HideModuleName> Public Module Extensions

        ''' <summary>
        ''' Create the substitution strategy object from the <see cref="Strategies"/> enum value.
        ''' </summary>
        ''' <typeparam name="genome">The chromosome type of the genetic algorithm.</typeparam>
        ''' <param name="strategy">The target substitution strategy.</param>
        ''' <returns>
        ''' An <see cref="IStrategy(Of Chr)"/> object; the 
        ''' <see cref="Strategies.Naive"/> strategy will be used when the 
        ''' <paramref name="strategy"/> value is unknown.
        ''' </returns>
        <Extension>
        Public Function GetStrategy(Of genome As {Class, Chromosome(Of genome)})(strategy As Strategies) As IStrategy(Of genome)
            Select Case strategy
                Case Strategies.EliteCrossbreed
                    Return New EliteReplacement(Of genome)
                Case Else
                    Return New SimpleReplacement(Of genome)
            End Select
        End Function
    End Module
End Namespace
