Namespace Kernel.GeneticAlgorithm
    ''' <summary>
    ''' This interface represents everything we need from a neuron in this
    ''' Genetic Algorithm sample. We need it to execute and give a result
    ''' for an input, we need it to be capable of reproducing and, for
    ''' performance reasons, we want it to say how complex it is. The
    ''' more complex cells lose points when analyzing how good it is the
    ''' result generated by them (if they didn't found the result... in that
    ''' case, they are the winners independently on how complex they are).
    ''' </summary>
    Public Interface INeuron
        ReadOnly Property Complexity() As Integer

        Function Execute(input As Integer) As System.Nullable(Of Integer)

        Function Reproduce() As INeuron
    End Interface
End Namespace