<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <AssemblyName>test</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <OutputType>Exe</OutputType>
    <StartupObject>test.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Data\DataFrame\dataframework-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\..\gr\Drawing-net4.8\Drawing-net4.8.vbproj" />
    <ProjectReference Include="..\..\..\..\gr\Microsoft.VisualBasic.Imaging\imaging.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\..\mime\text%html\html_netcore5.vbproj" />
    <ProjectReference Include="..\..\..\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\..\Visualization\Plots\plots-netcore5.vbproj" />
    <ProjectReference Include="..\..\DataMining\DataMining.NET5.vbproj" />
    <ProjectReference Include="..\HCTreePlot\HCTreePlot.vbproj" />
    <ProjectReference Include="..\hierarchical-clustering\hctree.NET5.vbproj" />
  </ItemGroup>
 </Project>