#Region "Microsoft.VisualBasic::d593f1c22ac916c3ca4cad11b5bba340, Data_science\Mathematica\Math\Math\Distributions\Gaussian.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 68
    '    Code Lines: 36 (52.94%)
    ' Comment Lines: 25 (36.76%)
    '    - Xml Docs: 84.00%
    ' 
    '   Blank Lines: 7 (10.29%)
    '     File Size: 2.86 KB


    '     Module Gaussian
    ' 
    '         Function: (+2 Overloads) Gaussian, (+2 Overloads) rnorm, StandadizedGaussianFunction
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports System.Runtime.CompilerServices
Imports Microsoft.VisualBasic.Math.LinearAlgebra
Imports rand = Microsoft.VisualBasic.Math.RandomExtensions
Imports std = System.Math

Namespace Distributions

    ''' <summary>
    ''' ##### Gaussian function
    ''' 
    ''' https://en.wikipedia.org/wiki/Gaussian_function
    ''' </summary>
    Public Module Gaussian

        ''' <summary>
        ''' 
        ''' </summary>
        ''' <param name="x"></param>
        ''' <param name="A">is the height of the curve's peak</param>
        ''' <param name="mu">is the position of the center of the peak</param>
        ''' <param name="sigma">(the standard deviation, sometimes called the Gaussian RMS width) 
        ''' controls the width of the "bell"</param>
        ''' <returns></returns>
        Public Function Gaussian(x#, A#, mu#, sigma#) As Double
            Dim p# = ((x - mu) ^ 2) / (2 * (sigma ^ 2))
            Dim fx# = A * std.Exp(-p)
            Return fx
        End Function

        Public Function Gaussian(x As IEnumerable(Of Double), A#, mu#, sigma#) As Double()
            Dim offset = SIMD.Subtract.f64_op_subtract_f64_scalar(x.ToArray, mu)
            Dim num = (2 * (sigma ^ 2))
            Dim pow = SIMD.Exponent.f64_op_exponent_f64_scalar(offset, 2)
            Dim p = SIMD.Divide.f64_op_divide_f64_scalar(pow, num)
            Dim exp = SIMD.Exponent.f64_exp(SIMD.Subtract.f64_scalar_op_subtract_f64(0, p))
            Dim gauss = SIMD.Multiply.f64_scalar_op_multiply_f64(A, exp)
            Return gauss
        End Function

        Public Function StandadizedGaussianFunction(diff As Double, devi As Double) As Double
            ' exp(-(diff/devi)^2 / 2)
            Dim result = std.Exp(-0.5 * std.Pow(diff / devi, 2))
            Return result
        End Function

        <MethodImpl(MethodImplOptions.AggressiveInlining)>
        Public Function rnorm(x As Vector, m As Double, sd As Double) As Vector
            Return New Vector(x.Select(Function(n) pnorm.ProbabilityDensity(n, m, sd)))
        End Function

        ''' <summary>
        ''' Returns a vector with specific parameters normal distribution of length n elements.
        ''' Distribution data was generated by the n length random seeds as the normal distribution 
        ''' inputs.
        ''' </summary>
        ''' <param name="n"></param>
        ''' <param name="m"></param>
        ''' <param name="sd"></param>
        ''' <returns></returns>
        ''' 
        <MethodImpl(MethodImplOptions.AggressiveInlining)>
        Public Function rnorm(n As Integer, m As Double, sd As Double) As Vector
            Return Enumerable.Range(0, n) _
                .Select(Function(x) rand.NextGaussian(m, sd)) _
                .AsVector
        End Function
    End Module
End Namespace
