<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.cs</DefaultItemExcludes>
    <AssemblyName>Microsoft.VisualBasic.MachineLearning.Bootstrapping</AssemblyName>
    <RootNamespace>Microsoft.VisualBasic.MachineLearning.Bootstrapping</RootNamespace>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Raw data processing for MachineLearning</Title>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;Rsharp_app_release</Configurations>
    <Version>1.0.9742.6623</Version>
    <AssemblyVersion>1.0.9742.6623</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\nlp\word2vec\word2vec.vbproj" />
    <ProjectReference Include="..\..\Graph\graph-netcore5.vbproj" />
    <ProjectReference Include="..\..\Mathematica\Math\Math\Math.NET5.vbproj" />
  </ItemGroup>
</Project>